version: '3.8'

services:
  astroguide:
    build:
      context: .
      dockerfile: Dockerfile
      # Vous pouvez passer des arguments de build ici :
      # args:
      #   VITE_API_URL: "votre_valeur"
    container_name: astroguide-app
    ports:
      - "2502:80"
    restart: unless-stopped
